Repository gdsc-ipsacademy/Competitive_Programming, pull requests merged in 2023-10, with the labels that each got.

#5 Added selection sort algorithm.
  algorithms/selection-sort/README.MD
  algorithms/selection-sort/selection_sort.cpp
Labels: hacktoberfest-accepted

#4 Added new algorithm: Merge-Sort | Fixing Issue #2
  algorithms/merge-sort/README.md
  algorithms/merge-sort/merge_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added Insertion Sort Algorithm
  algorithms/insertion-sort/README.md
  algorithms/insertion-sort/insertion_sort.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 Added Quick Sort Algorithm
  algorithms/quick-sort/README.md
  algorithms/quick-sort/quick_sort.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 Added Selection Sort in python.
  algorithms/selection-sort/selection_sort.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#19 Added new algorithm: radix-sort
  algorithms/radix-sort/radix-sort.cpp
  algorithms/radix-sort/readme.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Adding Stack Data Structure and README
  data structures/stack/README.md
  data structures/stack/stack.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 Added new algorithm: bubble-sort
  algorithms/bubble-sort/bubble-sort.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 Added bubble sort code and README file for it
  algorithms/bubble-sort/README.MD
  algorithms/bubble-sort/bubble-sort.cpp
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#25 added snippet to convert decimal to binary
  cp templates/cpp/decimal-to-binary.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 Create lcm.cpp
  cp templates/cpp/lcm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#43 [Feat]:Added More Data Structures
  algorithms/Recursion/Last_Occur_Of_char.cpp
  algorithms/Recursion/Print_SubArray.cpp
  algorithms/Recursion/Reverse_string.cpp
  others/Map and Trie1.cpp
  others/Map and Tries2.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#34 added subsequence problem
  problems/subsequence.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added one more algorithm which is Kadane's Algorithm
  algorithms/Kadane's Algorithm/Main.java
  algorithms/Kadane's Algorithm/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#30 Create subset-sum-snippet.cpp
  problems/subset-sum.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Added new algorithm: [fenwick-tree,kmp,karatsuba]
  cp templates/cpp/kmp-snippet.cpp
  cp templates/java/karatsuba-snippet.java
  data structures/fenwick tree/fenwick-tree.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
